#+title: JANS: Just Another Network Server

* Description
:PROPERTIES:
:ID:       280135a0-2cff-4e93-8679-7d1a6d56b7b2
:END:
This script installs the following software:
- [[https://sonarr.tv/][Sonarr]]
- [[https://radarr.video/][Radarr]]
- [[https://lidarr.audio][Lidarr]]
- [[https://readarr.com/][Readarr]]
- [[https://jellyfin.org/][Jellyfin]]
- [[https://min.io/][MinIO]]
- [[https://www.kavitareader.com/][Kavita]
- [[https://www.navidrome.org/][Navidrome]
- [[https://doublecmd.sourceforge.io/][Doublecommander]]
- [[https://www.qbittorrent.org/][qBittorrent- Vuetorrent UI]]
- [[https://www.bazarr.media/][Bazarr]]
- [[https://github.com/Prowlarr/Prowlarr][Prowlarr]]
- [[https://www.portainer.io/][Portainer]]

With this combination, you can create a fully functional network server that is going to download,
categorize, subtitle and serve your favorite shows, movies, audio and books as well as use as a document 
store on your network 

* Features
:PROPERTIES:
:ID:       0e072c32-3158-4961-869c-49920090f3d5
:END:
In no particular order:
- *Automatic shows/movies download*: Just add your shows and movies to the watch list and it should
  automatically download the files when they are available.
- *Automatic clasification and organization*: Your media files should be completely organized by default.
- *Automatic subtitles download*: Self explanatory. Your media server should automatically download
  subtitles in the languages you choose, if they are available.
- *Support for Web, Android, iOS, Android TV and whatever that can support Emby*: Since we are
  leveraging from Emby, you should be able to watch your favorite media almost anywhere.

* Dependencies
:PROPERTIES:
:ID:       01577a0a-852e-481a-b9b3-791b68594f96
:END:
You need to have:
- [[https://www.docker.com/][docker]]
- [[https://docs.docker.com/compose/][docker-compose]]

If you haven't installed them, don't worry! The script will attempt to run both installations (it only
works in Debian and Ubuntu!)

* Before running
:PROPERTIES:
:ID:       1c609bfc-4e6e-4fd8-8129-1b722fd7cda8
:END:
Before installing, make sure you have:
- *An installation location*: The script is going to ask you for a install location, but it will default
  to ~/opt/yams~. Just make sure your current user has permissions to write on the selected directory.
- *A media folder*: This is the folder where all your files are going to be downloaded and categorized. If
  you choose ~/srv/media~, the script is going to create the following folders:
  + ~/srv/media/tv~: For your TV shows
  + ~/srv/media/movies~: For your movies
  + ~/srv/media/music~: For your music
  + ~/srv/media/books~: For your books
  + ~/srv/media/downloads~: For your torrent downloads
  + ~/srv/media/blackhole~: For your torrents blackhole
- *A regular user to run and own the media files*: You shouldn't use ~root~ for this user, but I'm not
  your father, nothing is going to stop you lol

* To run
:PROPERTIES:
:ID:       a0417c61-3fd8-40a0-9385-6c5aaed37337
:END:
#+begin_src bash
$ git clone https://gitlab.com/rogs/jans.git
$ cd jans
$ ./install.sh
#+end_src

And follow the instructions.


So far, this is tested in Debian 11 and Ubuntu 22.04.

* Usage
:PROPERTIES:
:ID:       9e995141-b386-4962-9842-7209bedc5651
:END:
When the script finishes installing without issues, just run:
#+begin_src
$ yams
yams - Yet Another Media Server

Usage: yams [--help|restart|stop|start]
options:
--help     displays this help message
restart    restarts yams services
stop       stops all yams services
start      starts yams services
destroy    destroy yams services so you can start from scratch
#+end_src
* todo [3/17]
:PROPERTIES:
:ID:       eba4712e-fa8a-42c8-bc32-b593141c99a4
:END:
(in order)

- [X] Support for multiple media servers (Jellyfin and Plex). [Done ✅]
- [X] Add [[https://www.portainer.io/][Portainer]]. [Done ✅]
- [ ] Add update functionality (~yams update~). [Working on it 👨‍💻]
- [ ] Consider moving to Alpine images (might not be possible without a big change on the docker-compose file).
- [ ] Add multiple download clients to choose from.
- [ ] Add Jackett as an "yams extra".
- [ ] Add [[https://github.com/Fallenbagel/jellyseerr][jellyseer]] or [[https://ombi.io/][Omby]].
- [ ] Add a dashboard like [[https://docs.organizr.app/installation/installing-organizr][Organizr]].
- [X] Consider adding [[https://lidarr.audio/][Lidarr]] and [[https://readarr.com/][Readarr]]. [Done ✅] Thanks to [[https://gitlab.com/jataggart][Jay Taggart]]!
- [ ] Support for qBittorrent themes (VueTorrent).
- [ ] Support for Wireguard.
- [ ] Check [[https://filebrowser.org/][Filebrowser]].
- [ ] Investigate [[https://github.com/FlareSolverr/FlareSolverr][FlareSolverr]].
- [ ] Check [[https://github.com/Unpackerr/unpackerr][unpackerr]].
- [ ] Check [[https://github.com/Flemmarr/Flemmarr][Flemarr]].
- [ ] Check usenet.
- [ ] Check [[https://github.com/hrfee/jfa-go][Jellyfin Accounts Go]].
