#+title: JANS: Just Another Network Server

This is a highly customized network server with media functionality.

* Description
:PROPERTIES:
:ID:       280135a0-2cff-4e93-8679-7d1a6d56b7b2
:END:
This script installs the following software:
- [[https://sonarr.tv/][Sonarr]]
- [[https://radarr.video/][Radarr]]
- [[https://lidarr.audio][Lidarr]]
- [[https://readarr.com/][Readarr]]
- [[https://jellyfin.org/][Jellyfin]]
- [[https://min.io][MinIO]]
- [[https://doublecmd.sourceforge.io/][DoubleCommander]]
- [[https://www.kavitareader.com/][Kavita]]
- [[https://www.navidrome.org/][Navidrome]]
- [[https://www.qbittorrent.org/][qBittorrent -VueTorrent UI]]
- [[https://www.bazarr.media/][Bazarr]]
- [[https://github.com/Prowlarr/Prowlarr][Prowlarr]]
- [[https://www.portainer.io/][Portainer]]

With this combination, you can create a fully functional media server that is going to download,
categorize, subtitle and serve your favorite shows, movies, audio and books as well as being used as document 
storage on local network (MinIO).

* Features
:PROPERTIES:
:ID:       0e072c32-3158-4961-869c-49920090f3d5
:END:
In no particular order:
- *Automatic shows/movies download*: Just add your shows and movies to the watch list and it should
  automatically download the files when they are available.
- *Automatic clasification and organization*: Your media files should be completely organized by default.
- *Automatic subtitles download*: Self explanatory. Your media server should automatically download
  subtitles in the languages you choose, if they are available.
- *Support for Web, Android, iOS, Android TV and whatever that can support Jellyfin*: Since we are
  leveraging from Jellyfin, you should be able to watch your favorite media almost anywhere.
- *Support for Document storage like Amazon S3 via MinIO*: Since we are
  leveraging from MinIO, you should be able to store Documents, photos and your pictures on your self hosted cloud storage.
  
* Dependencies
:PROPERTIES:
:ID:       01577a0a-852e-481a-b9b3-791b68594f96
:END:
You need to have:
- [[https://www.docker.com/][docker]]
- [[https://docs.docker.com/compose/][docker-compose]]

The script will attempt to run both installations (it only works in Debian and Ubuntu!)

* Before running
:PROPERTIES:
:ID:       1c609bfc-4e6e-4fd8-8129-1b722fd7cda8
:END:
Before installing, make sure you have:
- *An installation location*: The script is going to ask you for a install location, but it will default
  to ~/opt/jans~. Just make sure your current user has permissions to write on the selected directory.
- *A media folder*: This is the folder where all your files are going to be downloaded and categorized. If
  you choose ~/srv/media~, the script is going to create the following folders:
  + ~/srv/media/tv~: For your TV shows
  + ~/srv/media/movies~: For your movies
  + ~/srv/media/music~: For your music
  + ~/srv/media/books~: For your books
  + ~/srv/media/downloads~: For your torrent downloads
  + ~/srv/media/blackhole~: For your torrents blackhole
  + ~/srv/media/data~: For your MinIO storage
- *A regular user to run and own the media files*: You shouldn't use ~root~ for this user

* To run
:PROPERTIES:
:ID:       a0417c61-3fd8-40a0-9385-6c5aaed37337
:END:

#+begin_src bash
$ git clone https://github.com/gurukewl/jans.git
$ cd jans
$ ./install.sh
#+end_src

And follow the instructions.

So far, I've tested this in Debian 11 and Ubuntu 22.04.

* Usage
:PROPERTIES:
:ID:       9e995141-b386-4962-9842-7209bedc5651
:END:
When the script finishes installing without issues, just run:
#+begin_src
$ yams
jans - Just Another Network Server

Usage: jans [--help|restart|stop|start|update|destroy]
options:
--help     displays this help message
restart    restarts jans services
stop       stops all jans services
start      starts jans services
update     updates jans srvices
destroy    destroy jans services so you can start from scratch
#+end_src
